apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:/Users/Moe/Desktop/MA/CND/CASE_CND/k8s/data"