spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      authentication-database: admin
      username: YWRtaW4=
      password: YWRtaW4=
      database: test_db
      port: 27017
      host: casemongo
