apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: casemongo
  name: casemongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casemongo
  strategy: {}
  template:
    metadata:
      labels:
        app: casemongo
    spec:
      containers:
        - image: mongo:5.0.14
          name: casemongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: admin

          volumeMounts:
            - name: mongo-data-dir
              mountPath: /data/db
      volumes:
        - name: mongo-data-dir
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: casemongo
  name: casemongo
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: casemongo
