# This workflow will build a Python project Docker Container, and push it to Docker Hub


name: Build MagicMirror 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MagicMirror
    steps:
    - uses: actions/checkout@v3
    - name: Build MagicMirror Docker image
      run: docker build . --file ./Dockerfile --tag moritzzeitler/case:casemagicmirror
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker Image to docker hub
      run: docker push moritzzeitler/case:casemagicmirror
