name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build EventService Docker image
      run: docker build . --file ./EventService/Dockerfile --tag caseeventservice
    - name: Push Docker Image to docker hub
      run: docker push moritzzeitler/case:caseeventservice
      
